version: 2.0
config-version: 2
name: shop
profile: snowflake
repositories:
  - name: dbt
    package: dbt-core
    version: 1.1.0

model-paths:
  - "models"
  - "data"

target-path: "target"

models:
  my_model:
    materialized: table
    
    